# Backend
backend = "egl";
vsync = true;
use-damage = true;
dithered-present = false;

# Disable all effects
fading = false;
shadow = false;
blur-background = false;
corner-radius = 0;

# Opacity (all fully opaque)
inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;

# Misc
detect-client-opacity = true;
use-ewmh-active-win = true;
detect-transient = true;
log-level = "warn";

